apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- master-deployment.yaml
- master-service.yaml
- slave-deployment.yaml
- slave-service.yaml
namespace: ci-argocd-gke
commonLabels:
  app: ci-argocd-gke
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: 6a7263b34a90ab7b0e6d6665c84b6938f748480e
