apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- master-deployment.yaml
- master-service.yaml
- slave-deployment.yaml
- slave-service.yaml
namespace: cicd-gke
commonLabels:
  app: cicd-gke
images:
- name: cicd-gke
  newName: cicd-gke
  newTag: cicd-gke
