apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- master-deployment.yaml
- master-service.yaml
- slave-deployment.yaml
- slave-service.yaml
namespace: cicd-gke-green
commonLabels:
  app: cicd-gke-green
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: ffd62fa31ca5d73ce607ffca2153763e975197a9
