apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- master-deployment.yaml
- master-service.yaml
- slave-deployment.yaml
- slave-service.yaml
namespace: cicd-gke-blue
commonLabels:
  app: cicd-gke-blue
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: c6bac0c2c0dcde7d9bcafd96fb59133b9e5271f0
