apiVersion: v1
kind: Service
metadata:
  labels:
    app: master
  name: master
  namespace: cicd-gke
spec:
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app: master
