apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: master
  name: master
  namespace: cicd-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - args:
            - uvicorn
            - master:app
            - --host=0.0.0.0
            - --port=8000
            - --log-config=log_conf.yaml
          env:
            - name: HEARTBEATS
              value: "10"
          image: serhii714/cicd-gke:latest
          name: master
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
      restartPolicy: Always
