apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: slave
  name: slave
  namespace: cicd-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
        - args:
            - uvicorn
            - slave:app
            - --host=0.0.0.0
            - --port=8000
            - --log-config=log_conf.yaml
          env:
            - name: HEARTBEATS
              value: "10"
          image: serhii714/cicd-gke:latest
          name: slave
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
