# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Replicated log + argocd

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 'main'


jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:

    - 
      name: Checkout repository
      uses: actions/checkout@v4

    - 
      name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"

    - 
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - 
      name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
     
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        flake8 tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - 
      name: Test with pytest
      run: |
        python -m pytest


  build:
    name: Build
    needs: tests
    runs-on: ubuntu-latest

    steps:

    - 
      name: Checkout repository
      uses: actions/checkout@v4

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/cicd-gke:${{ github.sha }}, ${{ vars.DOCKERHUB_USERNAME }}/cicd-gke:latest


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write 

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4

      - 
        name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
      - 
        name: Update Kubernetes resources
        run: |
          cd k8s
          kustomize edit set namespace ci-argocd-gke
          kustomize edit set label app:ci-argocd-gke
          kustomize edit set image cicd-gke=${{ vars.DOCKERHUB_USERNAME }}/cicd-gke:${{ github.sha }}
          cat kustomization.yaml
      - 
        name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker tag!"

      - 
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
