# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Replicated log - iteration 3

on:
  push:
    branches: 
      - 'main'
    paths: 
      - 'iteration3/**'
      - '.github/workflows/ci-cd-python-app.yml'

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v4

    - 
      name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"

    - 
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f iteration3/requirements.txt ]; then pip install -r iteration3/requirements.txt; fi

    - 
      name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 iteration3/app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 iteration3/tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 iteration3/app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        flake8 iteration3/tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - 
      name: Test with pytest
      run: |
        cd iteration3
        python -m pytest

  build:
    name: Build
    needs: tests
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./iteration3/
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cicd-gke:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/cicd-gke:latest

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      